# syntax=docker/dockerfile:1.4

# ===================================
#       BUILD ARGUMENTS
# ===================================
ARG NODE_VERSION=22
ARG ALPINE_VERSION=3.19

# ===================================
#       PHASE 1 - DEPENDENCIES
# ===================================
FROM node:${NODE_VERSION} AS deps
WORKDIR /app

RUN npm i -g bun

# Copy package files and remove version
COPY package.json ./

RUN bun install --force
