@echo off
:: GoClaw Quick Setup — interactive wizard for Windows.
::
:: Usage:
::   scripts\setup.bat              (interactive)
::   scripts\setup.bat --mode docker
::   scripts\setup.bat --mode native
::   scripts\setup.bat --mode lite
::
:: Modes:
::   docker  — GoClaw + PostgreSQL in Docker (recommended, no install needed)
::   native  — GoClaw binary on this host, connecting to your own PostgreSQL
::   lite    — Desktop app with embedded SQLite (no PostgreSQL needed)

setlocal EnableDelayedExpansion

set "REPO=nextlevelbuilder/goclaw"
set "MODE="
set "PG_SOURCE="
set "WITH_UI=0"
set "GOCLAW_PORT=18790"
set "GOCLAW_UI_PORT=3000"
set "DATA_DIR=.\goclaw-data"

:: ── Parse args ──
:parse_args
if "%~1"=="" goto :args_done
if /i "%~1"=="--mode"    ( set "MODE=%~2"      & shift & shift & goto :parse_args )
if /i "%~1"=="--pg"      ( set "PG_SOURCE=%~2" & shift & shift & goto :parse_args )
if /i "%~1"=="--with-ui" ( set "WITH_UI=1"     & shift              & goto :parse_args )
if /i "%~1"=="--help"    goto :show_help
if /i "%~1"=="-h"        goto :show_help
echo   Unknown option: %~1
exit /b 1
:args_done

:: ── Detect tools ──
set "HAS_DOCKER=0"
set "HAS_GOCLAW=0"

docker compose version >nul 2>&1 && set "HAS_DOCKER=1"
where goclaw >nul 2>&1           && set "HAS_GOCLAW=1"

:: ── Banner ──
echo.
echo ╔══════════════════════════════════════════════╗
echo ║          GoClaw Setup Wizard                 ║
echo ╚══════════════════════════════════════════════╝
echo.

:: ── Mode selection ──
if not "!MODE!"=="" goto :run_mode

echo    Choose deployment mode:
echo.
echo    1) Docker      — GoClaw + Postgres in containers  (recommended, no install needed)
echo    2) Native      — GoClaw binary on this host       (you manage PostgreSQL)
echo    3) Lite        — Desktop app with embedded SQLite (no PostgreSQL needed)
echo.

if "!HAS_DOCKER!"=="0" (
  echo    ^! Docker not detected — option 1 may not work.
  echo.
)

set /p "choice=   Choice [1-3, default=1]: "
if "!choice!"==""  set "choice=1"
if "!choice!"=="1" ( set "MODE=docker" & goto :run_mode )
if "!choice!"=="2" ( set "MODE=native" & goto :run_mode )
if "!choice!"=="3" ( set "MODE=lite"   & goto :run_mode )
if /i "!choice!"=="docker" ( set "MODE=docker" & goto :run_mode )
if /i "!choice!"=="native" ( set "MODE=native" & goto :run_mode )
if /i "!choice!"=="lite"   ( set "MODE=lite"   & goto :run_mode )
echo   Invalid choice.
exit /b 1

:run_mode
echo.

:: ════════════════════════════════════════════════
:: MODE: LITE
:: ════════════════════════════════════════════════
if /i "!MODE!"=="lite" (
  echo    ── GoClaw Lite — Desktop App ──
  echo.
  echo    Downloads the GoClaw Desktop app (SQLite embedded, no PostgreSQL needed).
  echo.
  echo    Download the latest release from:
  echo    https://github.com/!REPO!/releases
  echo.
  echo    Look for:  GoClaw-Setup-*.exe   (Windows installer)
  echo.
  exit /b 0
)

:: ════════════════════════════════════════════════
:: MODE: DOCKER
:: ════════════════════════════════════════════════
if /i "!MODE!"=="docker" (
  if "!HAS_DOCKER!"=="0" (
    echo   [ERROR] Docker is not installed or not running.
    echo   Install Docker Desktop from https://docker.com and retry.
    exit /b 1
  )

  echo    ── Docker Setup ──
  echo.

  :: PostgreSQL source
  if "!PG_SOURCE!"=="" (
    echo    PostgreSQL:
    echo    1) Bundled   — spin up a postgres container automatically ^(easiest^)
    echo    2) External  — connect to your own PostgreSQL ^(managed service, existing server^)
    echo.
    set /p "pg_choice=   Choice [1-2, default=1]: "
    if "!pg_choice!"==""  set "pg_choice=1"
    if "!pg_choice!"=="1" ( set "PG_SOURCE=bundled"  )
    if "!pg_choice!"=="2" ( set "PG_SOURCE=external" )
    if /i "!pg_choice!"=="bundled"  set "PG_SOURCE=bundled"
    if /i "!pg_choice!"=="external" set "PG_SOURCE=external"
    if "!PG_SOURCE!"=="" ( echo   Invalid choice. & exit /b 1 )
  )
  echo.

  :: Dashboard
  if "!WITH_UI!"=="0" (
    set /p "ui_choice=   Include web dashboard UI? [Y/n]: "
    if "!ui_choice!"==""  set "WITH_UI=1"
    if /i "!ui_choice!"=="y" set "WITH_UI=1"
    if /i "!ui_choice!"=="yes" set "WITH_UI=1"
  )
  echo.

  :: Create data dir
  if not exist "!DATA_DIR!" mkdir "!DATA_DIR!"
  echo    Created data directory: !DATA_DIR!

  set "ENV_FILE=!DATA_DIR!\.env"

  :: Generate secrets (using PowerShell for random hex)
  if not exist "!ENV_FILE!" (
    for /f %%i in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set "GATEWAY_TOKEN=%%i"
    for /f %%i in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(16))"') do set "ENCRYPTION_KEY=%%i"

    (
      echo # GoClaw environment — generated by setup.bat
      echo GOCLAW_GATEWAY_TOKEN=!GATEWAY_TOKEN!
      echo GOCLAW_ENCRYPTION_KEY=!ENCRYPTION_KEY!
      echo GOCLAW_PORT=!GOCLAW_PORT!
      echo GOCLAW_UI_PORT=!GOCLAW_UI_PORT!
    ) > "!ENV_FILE!"

    if "!PG_SOURCE!"=="bundled" (
      for /f %%i in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(12))"') do set "PG_PASSWORD=%%i"
      (
        echo POSTGRES_PORT=5432
        echo POSTGRES_USER=goclaw
        echo POSTGRES_PASSWORD=!PG_PASSWORD!
        echo POSTGRES_DB=goclaw
      ) >> "!ENV_FILE!"
      echo    [OK] Generated !ENV_FILE! with random secrets.
    ) else (
      echo    [OK] Generated !ENV_FILE!
    )
  ) else (
    echo    Using existing !ENV_FILE!
    :: Load existing env values
    for /f "usebackq tokens=1,* delims==" %%a in ("!ENV_FILE!") do (
      if not "%%a"=="" if not "%%a:~0,1%"=="#" set "%%a=%%b"
    )
  )

  :: External PG: collect DSN
  if "!PG_SOURCE!"=="external" (
    echo.
    echo    ── External PostgreSQL ──
    echo.
    echo    Enter your PostgreSQL connection string.
    echo    Format: postgres://user:pass@host:5432/dbname?sslmode=disable
    echo.

    if "!GOCLAW_POSTGRES_DSN!"=="" (
      set /p "GOCLAW_POSTGRES_DSN=   DSN: "
    ) else (
      echo    Using GOCLAW_POSTGRES_DSN from environment.
    )

    :: Warn about localhost
    echo !GOCLAW_POSTGRES_DSN! | findstr /i "localhost 127.0.0.1" >nul 2>&1
    if not errorlevel 1 (
      echo.
      echo    ^! DSN contains 'localhost' — inside Docker this resolves to the container itself.
      echo      Replace 'localhost' with 'host.docker.internal' to reach your host machine's PostgreSQL.
      echo.
      set "GOCLAW_POSTGRES_DSN=!GOCLAW_POSTGRES_DSN:localhost=host.docker.internal!"
      set "GOCLAW_POSTGRES_DSN=!GOCLAW_POSTGRES_DSN:127.0.0.1=host.docker.internal!"
      echo    Auto-replaced DSN: !GOCLAW_POSTGRES_DSN!
    )

    echo GOCLAW_POSTGRES_DSN=!GOCLAW_POSTGRES_DSN! >> "!ENV_FILE!"
    echo.
    echo    ^! Cannot verify pgvector from Windows without psql.
    echo      After startup, run:  docker compose exec goclaw goclaw doctor
  )

  :: ── Generate self-contained docker-compose.yaml ──
  set "COMPOSE_FILE=!DATA_DIR!\docker-compose.yaml"

  :: Write header
  (
    echo # GoClaw — generated by setup.bat
    echo # Edit as needed. Re-run setup.bat to regenerate.
    echo # Start:   docker compose up -d
    echo # Stop:    docker compose down
    echo # Logs:    docker compose logs -f goclaw
    echo # Migrate: docker compose exec goclaw goclaw migrate up
    echo.
    echo services:
  ) > "!COMPOSE_FILE!"

  :: Bundled postgres service
  if "!PG_SOURCE!"=="bundled" (
    (
      echo   postgres:
      echo     image: pgvector/pgvector:pg18
      echo     ports:
      echo       - "${POSTGRES_PORT:-5432}:5432"
      echo     environment:
      echo       POSTGRES_USER: ${POSTGRES_USER:-goclaw}
      echo       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-goclaw}
      echo       POSTGRES_DB: ${POSTGRES_DB:-goclaw}
      echo     volumes:
      echo       - postgres-data:/var/lib/postgresql/data
      echo     healthcheck:
      echo       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-goclaw} -d ${POSTGRES_DB:-goclaw}"]
      echo       interval: 5s
      echo       timeout: 5s
      echo       retries: 10
      echo     restart: unless-stopped
      echo.
    ) >> "!COMPOSE_FILE!"
  )

  :: GoClaw service
  (
    echo   goclaw:
    echo     image: ghcr.io/nextlevelbuilder/goclaw:latest
    echo     ports:
    echo       - "${GOCLAW_PORT:-18790}:18790"
    echo     env_file:
    echo       - .env
    echo     environment:
    echo       - GOCLAW_HOST=0.0.0.0
    echo       - GOCLAW_PORT=18790
    echo       - GOCLAW_CONFIG=/app/data/config.json
    echo       - GOCLAW_SKILLS_DIR=/app/data/skills
  ) >> "!COMPOSE_FILE!"

  if "!PG_SOURCE!"=="bundled" (
    echo       - GOCLAW_POSTGRES_DSN=postgres://$^{POSTGRES_USER:-goclaw^}:$^{POSTGRES_PASSWORD:-goclaw^}@postgres:5432/$^{POSTGRES_DB:-goclaw^}?sslmode=disable >> "!COMPOSE_FILE!"
  ) else (
    echo       - GOCLAW_POSTGRES_DSN=!GOCLAW_POSTGRES_DSN! >> "!COMPOSE_FILE!"
  )

  (
    echo     volumes:
    echo       - goclaw-data:/app/data
    echo       - goclaw-workspace:/app/workspace
    echo     extra_hosts:
    echo       - "host.docker.internal:host-gateway"
  ) >> "!COMPOSE_FILE!"

  if "!PG_SOURCE!"=="bundled" (
    (
      echo     depends_on:
      echo       postgres:
      echo         condition: service_healthy
    ) >> "!COMPOSE_FILE!"
  )

  (
    echo     security_opt:
    echo       - no-new-privileges:true
    echo     init: true
    echo     cap_drop:
    echo       - ALL
    echo     cap_add:
    echo       - SETUID
    echo       - SETGID
    echo       - CHOWN
    echo     tmpfs:
    echo       - /tmp:rw,noexec,nosuid,size=256m
    echo     restart: unless-stopped
    echo.
  ) >> "!COMPOSE_FILE!"

  :: Optional dashboard service
  if "!WITH_UI!"=="1" (
    (
      echo   goclaw-ui:
      echo     image: ghcr.io/nextlevelbuilder/goclaw-web:latest
      echo     ports:
      echo       - "${GOCLAW_UI_PORT:-3000}:80"
      echo     depends_on:
      echo       - goclaw
      echo     restart: unless-stopped
      echo.
    ) >> "!COMPOSE_FILE!"
  )

  :: Volumes block
  (
    echo volumes:
    echo   goclaw-data:
    echo   goclaw-workspace:
  ) >> "!COMPOSE_FILE!"

  if "!PG_SOURCE!"=="bundled" (
    echo   postgres-data: >> "!COMPOSE_FILE!"
  )

  :: Generate start.bat wrapper
  set "WRAPPER=!DATA_DIR!\start.bat"
  (
    echo @echo off
    echo :: GoClaw start — generated by setup.bat
    echo setlocal
    echo cd /d "%%~dp0"
    echo docker compose %%*
  ) > "!WRAPPER!"

  echo.
  echo ╔══════════════════════════════════════════════╗
  echo ║         Docker Setup Ready!                  ║
  echo ╚══════════════════════════════════════════════╝
  echo.
  echo    Config:   !COMPOSE_FILE!
  echo    Secrets:  !ENV_FILE!
  echo    Start:    !WRAPPER!
  echo.
  echo    ── Quick Start ──
  echo.
  echo    cd !DATA_DIR!
  echo    start.bat up -d
  echo.
  echo    ── First-time only: run migrations ──
  echo.
  echo    start.bat exec goclaw goclaw migrate up
  echo.
  if "!WITH_UI!"=="1" (
    echo    Gateway:   http://localhost:!GOCLAW_PORT!
    echo    Dashboard: http://localhost:!GOCLAW_UI_PORT!
  ) else (
    echo    Gateway:   http://localhost:!GOCLAW_PORT!
    echo    Tip: re-run with --with-ui to add the web dashboard
  )
  echo.
  exit /b 0
)

:: ════════════════════════════════════════════════
:: MODE: NATIVE BINARY
:: ════════════════════════════════════════════════
if /i "!MODE!"=="native" (
  echo    ── Native Binary Setup ──
  echo.

  if "!HAS_GOCLAW!"=="0" (
    echo    GoClaw binary not found.
    echo    Download the latest release from:
    echo    https://github.com/!REPO!/releases
    echo.
    echo    Look for:  goclaw-*-windows-amd64.zip
    echo    Extract goclaw.exe and add to PATH, then re-run this script.
    echo.
    exit /b 1
  )

  for /f "tokens=*" %%v in ('goclaw version 2^>nul') do set "GOCLAW_VER=%%v"
  echo    [OK] GoClaw installed: !GOCLAW_VER!
  echo.

  :: PostgreSQL DSN
  echo    ── Database Connection ──
  echo.
  echo    1) Enter DSN manually
  echo    2) Use GOCLAW_POSTGRES_DSN environment variable (already set)
  echo    3) I don't have PostgreSQL — show me options
  echo.

  set "PG_DSN=!GOCLAW_POSTGRES_DSN!"

  if not "!PG_DSN!"=="" (
    echo    Using GOCLAW_POSTGRES_DSN from environment.
    goto :native_pgvector_check
  )

  set /p "pg_opt=   Choice [1-3, default=1]: "
  if "!pg_opt!"=="" set "pg_opt=1"

  if "!pg_opt!"=="1" (
    echo.
    echo    Format: postgres://user:pass@host:5432/dbname?sslmode=disable
    set /p "PG_DSN=   PostgreSQL DSN: "
    goto :native_pgvector_check
  )
  if "!pg_opt!"=="2" (
    echo    GOCLAW_POSTGRES_DSN is not set. Set it and re-run.
    exit /b 1
  )
  if "!pg_opt!"=="3" (
    echo.
    echo    ── PostgreSQL Options ──
    echo.
    echo    Docker ^(fastest^):
    echo      docker run -d --name goclaw-pg -p 5432:5432 -e POSTGRES_PASSWORD=goclaw pgvector/pgvector:pg18
    echo.
    echo    Chocolatey:   choco install postgresql
    echo    Scoop:        scoop install postgresql
    echo    Installer:    https://www.postgresql.org/download/windows/
    echo.
    echo    Managed ^(free tier^): Supabase, Neon, Railway, Render
    echo      ^(Enable the 'vector' extension in your provider's dashboard^)
    echo.
    echo    After setting up PostgreSQL, re-run: scripts\setup.bat --mode native
    exit /b 0
  )
  echo   Invalid choice.
  exit /b 1

  :native_pgvector_check
  echo.
  echo    ^! Cannot verify pgvector from Windows without psql.
  echo      After startup, run:  goclaw doctor
  echo.

  echo    ── Running GoClaw Onboard Wizard ──
  echo.
  set "GOCLAW_POSTGRES_DSN=!PG_DSN!"
  goclaw onboard
  exit /b 0
)

echo   Unknown mode: !MODE!
exit /b 1

:: ════════════════════════════════════════════════
:show_help
echo GoClaw Quick Setup Wizard
echo.
echo Usage:
echo   scripts\setup.bat              (interactive)
echo   scripts\setup.bat --mode docker
echo   scripts\setup.bat --mode native
echo   scripts\setup.bat --mode lite
echo.
echo Modes:
echo   docker  GoClaw + PostgreSQL in Docker (recommended, no install needed)
echo   native  GoClaw binary on this host, connecting to your own PostgreSQL
echo   lite    Desktop app with embedded SQLite (no PostgreSQL needed)
exit /b 0
